### PR TITLE
first version of a preprocessing manager

### PR DESCRIPTION
**Pull request by jrmsgr**
First version of a preprocessing manager, i would need some feedback

### CODE REVIEW

**Comment by jrmsgr** [comment]
I completely changed what i have done, it is just not pushed yet.

**Comment by Ratoone** [comment]
No problem, push the changes whenever you're ready

**Comment by jrmsgr** [comment]
Here is the updated version of my work

**Comment by Ratoone** [comment]
Tests are not passing

**Review by Ratoone — APPROVED** [review]

**Pull request merged**
